AbhiPatel10/AISKCON-CONSTRUCTION

- css/style.css
- index.html
closes #2 
Tech Used-
`HTML` `CSS`
Additional Library- 
`Font Awesome`
> Make Responsive Footer #2

- css/style.css
- index.html
closes #25 
Icon position fixed
Previous PR was closed by mistake.
> Get in Touch section

- css/style.css
- index.html
- js/main.js
> FAQ section

- css/style.css
> Buttons made uniform in Contact With Our Expert page in mobile view

- css/style.css
- index.html
- js/main.js
closes #80 
1. Hamburger menu have single border
2. It is absolute 
3. It closes smoothly
> Hamburger menu modified

- docs/contribution.md
> contribution guidelines

- css/style.css
solved the hovering problem at footer
#123 
want to close the issue #123 (https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/issues/123) 
- [ √] Bug fix
- [ ✗ ] New feature
- [ ✗ ] Breaking change
- [ ✗ ] Documentation update
- [ ✗ ] Other (please describe)
- [ √] My code follows the code style of this project.
- [✗ ] My change requires a change to the documentation.
- [ ✗] I have updated the documentation accordingly.
- [✗ ] I have added tests to cover my changes.
- [√ ] All new and existing tests passed.
video file :
https://drive.google.com/file/d/1oEFa_9eEAjgFitzZqhNJVz96gO3ULzEO/view?usp=sharing
> solved the bug hovering on social links [GSSOC'23]

- README.md
Modified git clone link in Readme file
> Modified git clone link

- css/style.css
- js/main.js
Added a smooth slide transition to the accordion in the FAQ section
[add-transition-to-accordion.webm](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/97689140/98b15146-97b9-44d1-8a07-7fe0564fbf55)
> add smooth slide transitions to all FAQs

- css/style.css
- index.html
Added a cool gradient transition to the Book Us button
Closes #108 
- Button hover effect before
[button-transition-before.webm](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/97689140/9742e053-61c8-4e2f-af18-176302bf0fce)
- Button hover effect now
[button-transition-after.webm](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/97689140/827bde26-d998-4f8f-b8b9-3c97211c68f5)
> add gradient transition to Book Us button

- slotBooking/form.html
> redirecting to home page

- index.html
- js/main.js
I have fixed the glitch in the navbar and now the hamburger icon changes to the close button on click.
https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/105661636/fcb0f2c3-f382-4f51-999a-0e3f07db7ba1
> Resolved Issue #211 ; Fixed Glitch in Navbar Mobile View 

- css/style.css
#164 
Made navbar drop-downs translucent to allow better readability of the images below
Reduced opacity of the drop-down lists in the navbar so that the images below the navbar are more clearly visible.
> Navbar drop-downs translucent

- .idea/.gitignore
- .idea/AISKCON-CONSTRUCTION.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- README.md
Issue reference - #160 
Readme is updated with please suggest the changes if any.
Request to increase the level as I try my best to make readme attractive
> Readme is updated

- css/style.css
- index.html
- js/main.js
Added a custom chatbot that answers the FAQs of the website
[chatbot-integration.webm](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/97689140/607b8739-5ec1-46a6-b29d-75d9819b3753)
> add custom chatbot

- ServiceSection/index.html
- aboutUs/index.html
- contact/index.html
- css/style.css
- index.html
- repair/index.html
- repair/style.css
I have added gradient effect to the Buttons
#150 
https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/127978268/c68a6999-5d5e-4e91-a80b-dcc04a4175e6
> Hover Effect Added

- aboutUs/index.html
- aboutUs/style.css
Enhanced the formatting and readability of the "About Us" page - Our Commitment section by adding bullets to improve the clarity of the paragraph and enhance the user experience (UX).
Enhanced the clarity of the paragraph in the "About Us" page - Our Commitment section and added bullets for improved readability and user experience (UX).
/cc: @Neilblaze [13:22 IST | 10/06/23]
> Formatted the about page - Safety section

- aboutUs/index.html
- aboutUs/style.css
I made the following changes:
- Added a heading to the About Us hero section.
The About Us hero section was missing a heading, which made the section less clear to users. This pull request adds a heading to improve the visual and informational clarity of the section.
Please select the relevant option.
Please tick the relevant options.
> Added a heading to the About Us hero section.

- aboutUs/index.html
- aboutUs/style.css
- contribution.md
This pull request addresses the issue of improper formatting in the footer of the About Us page. It removes the unnecessary list style circle, improving the overall visual appearance and readability of the page.
I fixed the issue #354.
> Fixed the improper formatting in the footer of the About Us page

- css/style.css
Whenever the pag was scrolled , there was a movement in navbar as well. I solved it by changing the position 'sticky' of navabr to 'fixed' and then provided the required top, left, right value.
Now there is no movement in navbar when the page is scrolled.
> [Fixes #352] Fixed Navbar Scroll Problem

- .vscode/settings.json
- css/style.css
Enhanced the visual aesthetics of the scrollbar, creating a pleasing and delightful user interface.
https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/118369877/90fb5f05-b86a-4dae-ae68-4f443d137214
> Improved UI of scrollbar

- aboutUs/style.css
- contribution.md
Added a Contribution.md file to provide guidelines for contributing to the project. This file will help new contributors understand the process and requirements for making contributions. No dependencies are required for this change.
Fixed the issue #341 
Please select the relevant option.
Please tick the relevant options.
> Added Contribution File

- ServiceSection/index.html
- aboutUs/index.html
- contact/index.html
- index.html
- repair/index.html
- [.] Other (Redirecting to home upon clicking on logo icon) ISSUE ID #316 
- [.] My code follows the code style of this project.
- [.] I have updated the documentation accordingly.
https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/120514593/6593707e-3a90-40a2-a833-2d04c4778eda
> Redirecting to home upon clicking on logo icon

- index.html
> favicon icon added

- ServiceSection/index.html
- aboutUs/index.html
- contact/index.html
This pull request addresses the issue of the favicon not being displayed on secondary pages.
I have made the necessary changes to ensure that the favicon is now visible on all secondary pages of the website.
Fixes #437
> Added Favicon to Secondary Pages

- css/style.css
The Issues are already listed in #441 with proper screenshots and captions.
Fixed 4 issues 
All are as expected mention in #441 
1. Make the two buttons vertically only for mobile.
2. Make the two buttons aligned horizontally for mobile without wrapping of text 
3. UI of the card handled, the spaces equally on the sides of the button
4. Make all four buttons align properly 
Please review and give your feedback 
Close #441 
GSSOC'23
> Enhanced UI on mobile #441

- ServiceSection/style.css
FIXES#430
old
new
@kartikayasija @Neilblaze please merge my pull request #435
> modified service section

- css/style.css
- index.html
At a specific pixel length the hamburger drop down is not closing by it's own so I corrected it all
> Correction in navbar

- index.html
This change resolves #474 by changing data-aos-duration to 500 
- [ ✓] Bug fix
- [ ✓] My code follows the code style of this project.
> Fix delay animation in general-info-card

- README.md
I fixed the typo from `dependancy` to `dependency`.
I fixed the broken heading which is `Techstacks:`
> Docs: Fix typo & broken heading in README.md

- ServiceSection/index.html
- aboutUs/index.html
- contact/index.html
- repair/index.html
> Added Github icon in about , contact , repair and ServiceSections
